# COMMENT
#PRINT("")  PRINTING
#A,S,D,F,G=1,2,3,"RAGAA",4
#print(" %s: first number is: %d and second number is: %d " %(F,A,S))
#print("ragaa %d" %(A))
#METHODS OF INECT VAIABLE IN STRING
#F,S="RAGAA",10
#A,B="3",4
#print("first num is {} and second num is  {}".format(A,B))
#print("first num is {s1} secon num is {f1}".format(s1=S ,f2=F))
#print('first num is', F, 'second num is', S)
#print('first num is '+ F + 'and second num is' + str(S))
#print('first num is '+ F 'second num is ' + F)
#MYNAME =input("hello enter ur name")
#print("my nameis"+ (MYNAME))
#A,B,C=input("enter 3 values").split("alaa",3)#METHOD CHANNNING
#print("vaue1" , A)
#print("vaue2" , B)
#print("vaue3" , C)
#ARITHMATIC OPERATIONS
a=10
b=20
#add
print(a+b)
#sub
print(a-b)
#exponentiation
print(a**b)
#floor division
print((2.999999//1))
#MOULAS
print(7%3)
#retional operators
a=10
b=20
print(a==b)
print(a!=b)
print(a<b)
print(a<=b)
#bitwise operation
a=60
b=13
c=0
c=a&b;
print("line 1-value of c is",c)
c =a | b
print("line 2-value of c is",c)
c =
#assignment operator
#complex datatype
